server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: myapp
  thymeleaf:
    prefix: file:src/main/resources/templates/ # ??? ?? ??
    suffix: .html # ??? ?? ???
  web:
    resources:
      static-locations: file:src/main/resources/static/